---
title: "Brief Introduction to Discourse Transcription"
subtitle: "LING 710"
author: "Bradley McDonnell"
institute: "UH Mānoa"
date: "2020/4/6 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


# What are the influences led to DT?

  - Chafe: the importance of hesitation, IU as the fundamental unit
  - Schegeloff, etc. (CA): Overlap, Pause, Turn Taking, etc.

---
# What is Discourse Transcription? 

  -"Discourse transcription can be defined as the process of creating a representation in writing of a speech event, in such a way as to make it accessible to discourse research."
  -"The transcriber must learn to listen for, classify, interpret, and notate the discourse features that are deemed significant."

---
# What is the goal of Discourse Transcription?

  - "The goal of discourse transcription, as we see it, is to represent in writing those aspects of a given speech event (as mediated through an audio or video record) which carry functional significance to the participants -- whether these are linguistic, paralinguistic, or nonlinguistic -- in a form that is accessible to analysis."
  - "The task is not, as it might appear at first blush, to produce a record of all the acoustic or physical (articulatory) events represented on a tape. The discourse transcriber seeks to write down what is significant to users of language,1 and for this must draw on a knowledge of the language transcribed, as well as of the culture that goes with it."

---
# What exactly do we transcribe? 

  - Everything? 
    - No. 
    - "One tries to record those cues which the interlocutors themselves attend to and make use of, in their process of monitoring and participating in the ongoing spoken interaction."
    - "Deciding what to transcribe, and what not to transcribe, is important not only for economizing effort, but also for focusing on fruitful research questions and the means required to answer them. This is the reason, we believe, that there will always be more than one way to transcribe spoken discourse: any transcription system will reflect its users' perspective and goals" (Ochs 1979).


---
# Transcription vs. coding

"Transcription is anything that you have to listen to the tape for; if you can mark something without listening to the tape, that’s no longer transcription but coding."

---
# What is an intonation unit? 

  - "a stretch of speech uttered under a single coherent intonation contour"
    1.	Pause
    2.	Pitch reset
    3.	Final lengthening
  -	Truncated intonation unit
    -	"...indicates that a speaker breaks off the intonation unit before completing its projected contour"

---
class: center, middle

# Let's get started!
